services:
  - type: web
    name: shopify-product-suggestions-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_SHOP_DOMAIN
        value: parallelapparel-uofthacksdemo.myshopify.com
      - key: PORT
        value: 3000
